version: "3.8"
services:
  app:
    build:
      context: .
    environment:
      - JWT_SHARED_SECRET
      - HTTP_PORT=${HTTP_PORT:-8080}
      - WORKERS
    ports:
      - ${HTTP_PORT:-8080}:${HTTP_PORT:-8080}
    command: ["gunicorn", "app.main:app"]
